name: shareddit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.3
  http: ^0.12.1
  flutter_downloader: ^1.4.4
  flutter_ffmpeg: ^0.2.10
  path_provider: ^1.6.10


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  test: ^1.14.7

flutter:

  uses-material-design: true
